.SUFFIXES: .cpp

CC = g++
# CFLAGS  = -Wall -O2
INCLUDE_DIR = ../include
CFLAGS  = -Wall -I$(INCLUDE_DIR)
LDLIBS  = -lm -lPQP -lemon

SRCS    = main.cpp

OBJECTS = main.o

TARGET = planning

CLEAN   = $(OBJECTS) $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(TARGET) $(LDLIBS)

.cpp.o:
	$(CC) ${CFLAGS} -c $<

run: $(TARGET)
	$(TARGET)

clean:
	/bin/rm -f $(CLEAN)

