.SUFFIXES: .cpp

CC = g++
CFLAGS  = -Wall `pkg-config --cflags opencv`
LDLIBS  = -lm -lemon

SRCS    = ordering.cpp

OBJECTS = ordering.o

TARGET = ordering

CLEAN   = $(OBJECTS) $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(TARGET) $(LDLIBS)

.cpp.o:
	$(CC) ${CFLAGS} -c $<

run: $(TARGET)
	$(TARGET)

clean:
	/bin/rm -f $(CLEAN)

