.SUFFIXES: .cpp

CC = g++
INCLUDE_DIR = "../include"
CFLAGS  = -Wall -I$(INCLUDE_DIR)
LDLIBS  = -lm -lemon

SRCS    = generate_valid_acc.cpp

OBJECTS = generate_valid_acc.o

TARGET = generate_accel

CLEAN   = $(OBJECTS) $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(TARGET) $(LDLIBS)

.cpp.o:
	$(CC) ${CFLAGS} -c $<

run: $(TARGET)
	$(TARGET)

clean:
	/bin/rm -f $(CLEAN)

